# Neuromorphic Cognitive Architecture
# 6-Database Brain Region Implementation
# Weight-Based Eidetic Memory System for 1000x Cognitive Amplification

version: '3.8'

services:
  # HIPPOCAMPUS: Redis - Episodic Memory, Rapid Encoding/Retrieval
  hippocampus:
    image: redis:7-alpine
    container_name: neuromorphic-hippocampus
    ports:
      - "6380:6379"
    volumes:
      - hippocampus_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-neuromorphic2025}
    networks:
      - neuromorphic_network
    restart: unless-stopped

  # NEOCORTEX: PostgreSQL - Semantic Memory, Structured Knowledge  
  neocortex:
    image: postgres:15-alpine
    container_name: neuromorphic-neocortex
    ports:
      - "5433:5432"
    volumes:
      - neocortex_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=neocortex
      - POSTGRES_USER=neuromorphic
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-neuromorphic2025}
    networks:
      - neuromorphic_network
    restart: unless-stopped

  # BASAL GANGLIA: Neo4j - Procedural Memory, Habit Patterns
  basal_ganglia:
    image: neo4j:5-community
    container_name: neuromorphic-basal-ganglia
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - basal_ganglia_data:/data
      - basal_ganglia_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-neuromorphic2025}
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
    networks:
      - neuromorphic_network
    restart: unless-stopped

  # THALAMUS: SurrealDB - Attention/Filtering, Multi-Modal (FIXED COMMAND SYNTAX)
  thalamus:
    image: surrealdb/surrealdb:latest
    container_name: neuromorphic-thalamus
    ports:
      - "8082:8000"
    volumes:
      - thalamus_data:/opt/surrealdb/data
    user: "1000:1000"
    command: start --bind 0.0.0.0:8000 --user neuromorphic --pass neuromorphic2025 file:///opt/surrealdb/data/neuromorphic.db
    networks:
      - neuromorphic_network
    restart: unless-stopped

  # AMYGDALA: MongoDB - Emotional Memory, Importance Weighting
  amygdala:
    image: mongo:7
    container_name: neuromorphic-amygdala
    ports:
      - "27018:27017"
    volumes:
      - amygdala_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=neuromorphic
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-neuromorphic2025}
      - MONGO_INITDB_DATABASE=amygdala
    networks:
      - neuromorphic_network
    restart: unless-stopped

  # Zookeeper for Kafka coordination
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: neuromorphic-zookeeper
    ports:
      - "2182:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - neuromorphic_network
    restart: unless-stopped

  # CEREBELLUM: Apache Kafka - Motor Memory, Execution Patterns (FIXED CLUSTER_ID)
  cerebellum:
    image: confluentinc/cp-kafka:latest
    container_name: neuromorphic-cerebellum
    ports:
      - "9093:9092"
    environment:
      - CLUSTER_ID=neuromorphic-cluster-001
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CLUSTER_ID=neuromorphic-cluster-001
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - cerebellum_data:/var/lib/kafka/data
    networks:
      - neuromorphic_network
    restart: unless-stopped

volumes:
  hippocampus_data:
  neocortex_data:
  basal_ganglia_data:
  basal_ganglia_logs:
  thalamus_data:
  amygdala_data:
  cerebellum_data:

networks:
  neuromorphic_network:
    driver: bridge
