# Neuromorphic Cognitive Architecture
# 6-Database Brain Region Implementation
# Weight-Based Eidetic Memory System for 1000x Cognitive Amplification

version: '3.8'

services:
  # HIPPOCAMPUS: Redis - Episodic Memory, Rapid Encoding/Retrieval
  hippocampus:
    image: redis:7-alpine
    container_name: neuromorphic-hippocampus
    ports:
      - "6379:6379"
    volumes:
      - hippocampus_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-neuromorphic2025}
    networks:
      - neuromorphic_network
    restart: unless-stopped

  # NEOCORTEX: PostgreSQL - Semantic Memory, Structured Knowledge  
  neocortex:
    image: postgres:15-alpine
    container_name: neuromorphic-neocortex
    ports:
      - "5432:5432"
    volumes:
      - neocortex_data:/var/lib/postgresql/data
      - ./sql/init_neocortex.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=neocortex
      - POSTGRES_USER=neuromorphic
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-neuromorphic2025}
    networks:
      - neuromorphic_network
    restart: unless-stopped

  # BASAL GANGLIA: Neo4j - Procedural Memory, Habit Patterns
  basal_ganglia:
    image: neo4j:5-community
    container_name: neuromorphic-basal-ganglia
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - basal_ganglia_data:/data
      - basal_ganglia_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-neuromorphic2025}
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
    networks:
      - neuromorphic_network
    restart: unless-stopped

  # THALAMUS: SurrealDB - Attention/Filtering, Multi-Modal
  thalamus:
    image: surrealdb/surrealdb:latest
    container_name: neuromorphic-thalamus
    ports:
      - "8000:8000"
    volumes:
      - thalamus_data:/data
    command: start --log trace --user neuromorphic --pass ${SURREAL_PASSWORD:-neuromorphic2025} file:/data/thalamus.db
    networks:
      - neuromorphic_network
    restart: unless-stopped

  # AMYGDALA: MongoDB - Emotional Memory, Importance Weighting
  amygdala:
    image: mongo:7
    container_name: neuromorphic-amygdala
    ports:
      - "27017:27017"
    volumes:
      - amygdala_data:/data/db
      - ./config/mongod.conf:/etc/mongod.conf
    environment:
      - MONGO_INITDB_ROOT_USERNAME=neuromorphic
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-neuromorphic2025}
      - MONGO_INITDB_DATABASE=amygdala
    networks:
      - neuromorphic_network
    restart: unless-stopped

  # CEREBELLUM: Apache Kafka - Motor Memory, Execution Patterns
  cerebellum:
    image: confluentinc/cp-kafka:latest
    container_name: neuromorphic-cerebellum
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - neuromorphic_network
    restart: unless-stopped

  # Zookeeper for Kafka coordination
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: neuromorphic-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - neuromorphic_network
    restart: unless-stopped

volumes:
  hippocampus_data:
  neocortex_data:
  basal_ganglia_data:
  basal_ganglia_logs:
  thalamus_data:
  amygdala_data:

networks:
  neuromorphic_network:
    driver: bridge